- when: inventory_hostname == groups['masters'][0]
  static: no
  include: ipsec-ca-sync-primary.yml

- name: Sync ipsec CA data to each master.
  when: inventory_hostname != groups['masters'][0]
  copy:
    dest: /etc
    src: /tmp/ipsec-ca
